# Site settings
title: Reyes Yang 的个人博客
description: Reyes Yang 的个人博客，记录了关于生活，编程的一些事情。
url: http://reyesyang.github.io/
author:
  name: Reyes Yang
  email: reyes.yang@gmail.com
  url: http://reyesyang.info

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
source: .
destination: ./_site
paginate: 10
paginate_path: /page/:num

# Default values
defaults:
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: post
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

sass:
  style: compressed

# Plugins
gems:
  - jekyll-paginate
  - jekyll-assets

# Custom variables
version: 1.1.0

# Options
reverse: false
