name: Reyes Yang's Blog
timezone: Asia/Shanghai
markdown: redcarpet
pygments: true
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
